### ISSUE TITLE
Login screen quickly rendered/replaced if user is already logged in

### ISSUE THREAD

**Issue by ecesena** [ParsePlatform/ParseReact#104]
I've built a simple app with react native that forces the user to log in/sign up before showing the actual content. The code is really simple, and follows the guide:
> With this, it is simple to gate application behavior on whether the user is logged in or not. For instance, if the value on this.data is null, render a log in dialog; if the value is not null, render the application functionality that requires a user.

```
  render: function() {
    ...
    return this.data.user ? 
    (
      <TabBarIOS ref="tabs">
        ...
      </TabBarIOS>
    ) :
    (
      <NavigatorIOS style={styles.nav} initialRoute={routeSignup} />
    );
}
```

The issue is that, if the user is already logged in and opens the app, the signup screen "flicks", i.e. quickly appears and is immediately replaced by the actual content.

I also tried passing the user as a prop (i.e. observing from the parent), but the behavior is the same.

Any idea on how to avoid rendering the signup screen?

**Comment by andrewimm** [comment]
This is due to the fact that React Native uses an asynchronous disk storage system, so we need to wait a brief second before the user is loaded.
I'm in the middle of refactoring some of these subscriptions, and I would like to propose changing the currentUser subscription to the following:
 - Value is `null` if there is no user
 - Value is a `Parse.User` if one has been fetched from cache / disk
 - Value is `undefined` if the login state is still unknown

This would let you write gating code as
```js
if (this.data.user === undefined) {
  // Still waiting
} else if (this.data.user === null) {
  // Show log in screen
} else {
  // Show the app
}
```

And, it still lets you gate other code on the truthiness of the current user

**Comment by ecesena** [comment]
That would be great - I look forward to the next release then.

**Comment by umfana** [comment]
+1 That would be fantastic! Been struggling with that part too lately.

**Comment by andrewimm** [comment]
This behavior is now supported in 0.5.0
The user subscription will return `undefined` when pending, and `null` when it has determined there is no current user on disk.
