### ISSUE TITLE
There is no current user user on a node.js server environment

### ISSUE THREAD

**Issue by Dids** [ParsePlatform/ParseReact#105]
I'm observing for changes to the current user, just like in the AnyBudget example:

```javascript
	observe: function()
	{
		return {
			user: ParseReact.currentUser
		};
	}
```

I'm also using NodeJS and Express to serve the HTML, JavaScript and static assets, but for some reason I keep getting the following error, and I have no idea why:

```
There is no current user user on a node.js server environment
```

I'm assuming this is a bug, since I'm not trying to get the current user in the NodeJS environment, nor am I initializing Parse with NodeJS. I'm simply using NodeJS to serve the files.

**Comment by andrewimm** [comment]
Are you using a browserify-type environment that supplies `process.version.NODE_VERSION`? The truthiness of this variable is how the JS SDK currently detects node environments.
It's odd that this is occurring, but you should be able to avoid the message by calling `Parse.User.enableUnsafeCurrentUser()`. That's how the current user is enabled in shared-memory environments like node servers.
I'd like to debug this, but the upcoming version of the Parse JS SDK will have separate npm modules for the browser, node, and React Native, so it shouldn't be a problem for long.

Closing since this is related to the JS SDK, not Parse+React, but feel free to continue the discussion.

**Comment by Dids** [comment]
Thank you, enabling the unsafe current user did indeed remove the error!

I am indeed using browserify and reactify to create a neat bundle of all the used libraries, which has worked perfectly for everything other than Parse.

I assumed this was due to an issue with Parse+React since I was observing ParseReact.currentUser, but glad to hear that's not the case.

**Comment by andrewimm** [comment]
Cool, thanks for the info. It's still puzzling why it thinks it's running on a node environment, though. I use Browserify to build all of the example apps with no issue.

**Comment by Dids** [comment]
Could it by any chance be caused by [Refreshify](https://github.com/alexanderGugel/refreshify)?
I actually do recall Parse working before, but I adjusted my development environment quite a few times, so right now I'm running a NodeJS+Express app that serves the files (for development only), but I also have to run Refreshify, otherwise I get errors/crashes as the page keeps trying to reload.
I'm guessing Refreshify injects something somewhere, but haven't had a chance to properly look yet.

I would've used watchify, but I don't think it supports rebuilding with browserify/reactify when a file changes.

**Comment by Dids** [comment]
Well the bad news is that for some weird reason I'm unable to replicate the issue anymore.
It's not Refreshify, since I tried with and without it and the issue seems to be gone.

I did previously have some extra Express middleware that I didn't need, so I'm hoping it was one of those. At any rate, this has magically fixed itself.

**Comment by andrewimm** [comment]
Cool. Thanks for digging deeper.
Anyways, as I mentioned, the next version of the JS SDK will come with explicit versions for node vs non-node, so this should never come up after that release.
