### ISSUE TITLE
Webpack friendly?

### ISSUE THREAD

**Issue by jenbennings** [ParsePlatform/ParseReact#11]
I'm trying to bring parse-react into my application by requiring it via webpack, but am being thrown a few errors/warnings:

```
ERROR in ./~/parse/~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Cannot resolve module 'child_process' in /Users/benjennings/path/to/project/node_modules/parse/node_modules/xmlhttprequest/lib
 @ ./~/parse/~/xmlhttprequest/lib/XMLHttpRequest.js 15:12-36

ERROR in ./~/parse/~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Cannot resolve module 'fs' in /Users/benjennings/path/to/project/node_modules/parse/node_modules/xmlhttprequest/lib
 @ ./~/parse/~/xmlhttprequest/lib/XMLHttpRequest.js 16:9-2
```

This is probably a bad idea—but I've I managed to solve the above by adding the following to my webpack config:

```js
  node: {
    fs: "empty",
    child_process: "empty"
  },
```
However I am still receiving these warnings on each successful build:

```
WARNING in ./~/parse-react/dist/parse-react.js
Critical dependencies:
5:483-490 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/parse-react/dist/parse-react.js 5:483-490

WARNING in ./~/parse/build/parse-latest.js
Critical dependencies:
1263:13-16 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./~/parse/build/parse-latest.js 1263:13-16

WARNING in ./~/parse/build/parse-latest.js
Module not found: Error: Cannot resolve module 'AsyncStorage' in /Users/benjennings/Documents/Coinbase/Web/central.coinbase.com/mark2/node_modules/parse/build
 @ ./~/parse/build/parse-latest.js 1956:21-40
```

Is there anything I should be including in my webpack config to avoid these warnings? Apologies in advance if this is more of a Webpack question than ParseReact.

**Comment by andrewimm** [comment]
Unfortunately, all of these are problems with packaging the Parse JS SDK, not Parse + React. I'd recommend you open a bug at https://parse.com/help and we can follow up from there. FWIW, the main issue you're seeing is due to a longtime inclusion of a dependency that I plan to replace in the next version of the JS SDK (1.4.2).
The warning you get specifically about `parse-react.js` being pre-built is just something that is going to happen. We do some interesting things at compilation time to make a difference between the `require`s we do in development and the `require`s we call at runtime, particularly to make React Native work.

**Comment by levitanong** [comment]
+1. I have the exact same problem. I've tried manually installing fs, but npm can't find child_process.

**Comment by levitanong** [comment]
Andrew, which dependencies do you intend to replace, and when do you plan to release the next version of the SDK?

**Comment by andrewimm** [comment]
We will be replacing `xmlhttprequest` in favor of something more lightweight that doesn't have such node dependencies (it uses `fs` and `child_process` for features that we don't use), but I'm still surveying the candidates.
I don't commit to release dates as a rule, but if this is the only change we want to include in the next incremental update, you can expect it within a couple of weeks. With the release of `1.3.5`, we changed the way `require` was called in order to avoid bundling unnecessary packages in non-node environments. After all, we only need to mock XHRs in node, the interface already exists in Webpack / Browserify / React Native. However, it seems that the AST-crawling of Webpack is a bit more clever than the others, and is still attempting to bundle any modules that are potentially required. I'm personally far more experienced with Browserify than Webpack, but I'll try to find something that can trick the latter as well. In the end, it may be that you have to use a `webpack.IgnorePlugin(/xmlhttprequest/)` when using Webpack with the Parse JS SDK.

**Comment by levitanong** [comment]
Awesome! I'll have a look at the IgnorePlugin thing. TBH, I can't say I'm familiar with either, and use webpack only for the hot reloading. Thanks for the speedy reply!

**Comment by twelvearrays** [comment]
Great News! Looking forward to the update.

**Comment by gmertk** [comment]
Adding `new webpack.IgnorePlugin(/xmlhttprequest/)` didn't work for me. I imported parse-latest.js with a script tag in my index.html and also added this in `webpack.config.js`

```
  externals:[{
    parse: 'Parse'
  }]
```

**Comment by vegetableman** [comment]
Instead of externals, just set ```noParse```, it would work.
```js
module: {
   noParse: /parse-latest.js/
}
```

**Comment by gmertk** [comment]
Thanks @vegetableman! I had tried `noParse`, but missed that it should be in `module`.

**Comment by jzumbrun** [comment]
+1 for webpack to get work. Having this same issue as others stated.

**Comment by andrewimm** [comment]
Parse 1.4.2 is now out. Grab it from npm, it'll work great in webpack, browserify, and React Native

**Comment by andrewimm** [comment]
(And of course, let me know if it doesn't work great)

**Comment by jzumbrun** [comment]
Yep 1.4.2 works!

**Comment by vegetableman** [comment]
@andrewimm :+1:

**Comment by ShuaiYuan87** [comment]
@andrewimm Sorry to piggy bag on this and I don't know if you will actually get a notification on a closed issue but I seem to still have the issue on Parse 1.4.2. And in the package.json file I still see xmlhttprequest listed as a dependency. Is that expected?
{
  "name": "parse",
  "version": "1.4.2",
  "description": "The Parse JavaScript SDK",
  "keywords": [
    "cloud",
    "mobile",
    "api"
  ],  
  "homepage": "http://www.parse.com",
  "bugs": {
    "url": "https://www.parse.com/help",
    "email": "community@parse.com"
  },  
  "files": [
    "build/parse-latest.js"
  ],  
  "main": "build/parse-latest.js",
  "dependencies": {
    "xmlhttprequest": ">=1.3.0"
  },  
Thanks!

**Comment by andrewimm** [comment]
@ShuaiYuan87 what environment are you building with, Webpack or something else? Even though it's listed as a dependency, Webpack should ignore it.
I'm currently working on the next release of the Parse JS SDK, and moving this dependency to the `"browser"` field of `package.json` should ensure that it's ignore by all the major packagers.

**Comment by ShuaiYuan87** [comment]
@andrewimm Thanks for your reply. It seems my issue is different from the "child_process" error but I swear I have somehow seen the same error too.
Right now I get 
var xhr = new Parse.XMLHttpRequest();
	                ^
TypeError: undefined is not a function
Any idea why? The code works fine in webpack dev server but not in production build.
