### ISSUE TITLE
Creating new Parse Object with Relation

### ISSUE THREAD

**Issue by naoisegolden** [ParsePlatform/ParseReact#129]
There seems to be no documentation on how to create a new row with a `Relation` using `ParseReact.Mutation.Create`. I resorted to this:

```js
function createRow(relatedObject, data) {
  ParseReact.Mutation.Create('objectClass', data)
    .dispatch()
    .then(function(newRow) {
      ParseReact.Mutation.AddRelation(newRow, 'relationColumn', relatedObject)
    });
}
```

Which is creating the new `objectClass` object/row, but the column `relationColumn` doesn't display the relation with the given `relatedObject`.

How is this done, preferably in one query with the `ParseReact.Mutation.Create`?

**Comment by adarshmuthappa** [comment]
+1

**Comment by kevinzzz007** [comment]
@naoisegolden @adarshmuthappa this repo hasn't been updated in half a month so I am not sure if Parse/Facebook is still supporting it... would love to hear from @andrewimm @philikon about this since they are the major contributors, in the mean time, I would recommend using the Javascript implementation to do most of the things that are not documented, such as relation...here is a link to relation in JS:
https://www.parse.com/docs/js/guide#relations

**Comment by kevinzzz007** [comment]
@naoisegolden @adarshmuthappa #27 might be helpful... I am trying it right now and will let you guys know if it works for me...

**Comment by kevinzzz007** [comment]
@naoisegolden @adarshmuthappa the following REST code worked for me to add relations, still investigating why the `ParseReact.Mutation.AddRelation` won't work

**Comment by kevinzzz007** [comment]
@naoisegolden @adarshmuthappa so my code is working with `ParseReact.Mutation.AddRelation`, here it is:
```
ParseReact.Mutation.AddRelation({
                          "className": newRow.className,
                          "objectId": newRow.id.objectId}, 'groceryRequestRelation',[{
                          "__type":"Pointer",
                          "className":"ClassThePointerPointingTo",
                          "objectId":"ObjectIdOfClassThePointerIsPointingTo"
                        }]).dispatch()
```
@naoisegolden you didn't put `.dispatch()` at the end of the `AddRelation` so that might be an issue.

Another thing that took me forever to figure out was I was using the wrong `objectId` within my `AddRelation`, I should be using the class that the pointer is pointing to, but I was using the `objectId` of the class that the `relation` belongs to...

**Comment by davidsims9t** [comment]
@naoisegolden Here's what I'm using to create a new object and add a relation:

ParseReact.Mutation.Create("ClassName", {key: value})
.dispatch().then((object) => {
ParseReact.Mutation.AddRelation(object, "relation", myRelationObject).dispatch().then(() => {
console.log("relation added")
})
})

I think when you add/remove a relation the objects your passing in need to be in the format {className: "ClassName", objectId: "objectId"}. Actually if you do a console.log() on an object you've just created or an object that you're observing in your observe() method, you will get a id parameter on the object that you can use for adding relations.

**Comment by adarshmuthappa** [comment]
Sweet! Thanks @kevinzzz007 @davidsims9t Looks like a dispatch() is required for AddRelation as well. Just checked and confirm it works now. Thanks guys!

**Comment by kevinzzz007** [comment]
@adarshmuthappa @davidsims9t I am trying to use react-native-parse to query the objects in a relation, but have to use the REST way to do it and it's really complex, do you guys know a better way to query objects in a relation in React Native?

**Comment by adarshmuthappa** [comment]
I haven't tried querying relations yet. Will try soon and post here if I come up with a solution.

**Comment by davidsims9t** [comment]
@kevinzzz007 I've successfully queried relations, you can do it by calling query.relations("myrelationcol").query(). You'll have to create a component and pass the query with the relational column as a prop if you want to observe the relational query. It seems that when you create a new relation, however, it doesn't update the component. I've read you can manually refresh the query by using this.refreshQueries() in your then() statement after dispatching, but I've haven't tried it yet. I hope that helps!

**Comment by kevinzzz007** [comment]
@davidsims9t thanks!  This really helps!  Could you share some code?  What you said makes sense, but I think some code would really help me since I am still a bit lost in what is the `query` object in `query.relations("myrelationcol").query()` and how do I create a new component specifically for the purpose of getting the relation data...thank you so much!

**Comment by kevinzzz007** [comment]
@davidsims9t I am getting this error:
`newQuery.relations is not a function`
from this code:
```
var newQuery = new Parse.Query('TableName');
console.log(newQuery.relations('RelationColumnName').query());
```
Thanks!

**Comment by davidsims9t** [comment]
@kevinzzz007 Sorry it's actually relation() not relations(), my mistake. So in my case I'm using a relational query by passing the query to my navigator props like this:

let self = this
    let query = new Parse.Query("MyClassName")
    query.get(myObjId, (myObject) => {
      let props = {
myObject: myObject
}
      self.props.navigator.push(props)
    })

And then to the component I'm navigating/segueing to my class looks like:

const MyDetailClass = React.createClass({
mixins: [ParseReact.Mixin],
observe() {
let query = this.props.route.myObject.relation("myRelationCol").query()

return {
relationData: query
}
}
})

**Comment by kevinzzz007** [comment]
@davidsims9t so for some reason I keep getting myobj.relation is not a function, it seems relation is not a function for a Parse object, do you know if relation is a function of something else? Thanks!

**Comment by kevinzzz007** [comment]
@davidsims9t it's working now!  Thanks so much!  I will finish the code and post my code here for future reference :-)

**Comment by naoisegolden** [comment]
> you didn't put `.dispatch()` at the end of the `AddRelation`.

Works for me too. Closing.
