### ISSUE TITLE
ParseReact w/o React dependencies?

### ISSUE THREAD

**Issue by chadobado** [ParsePlatform/ParseReact#2]
Are there any plans to release a version of this library (with some of its more flux/relay-centric approaches) without a direct dependency on react? 

If not, how tightly coupled are these dependencies and (realistically) can the they be separated?

For our products, we had to build a custom mobile framework, inspired by React, and have been attempting to build an immutable DataStore (based on flux and relay patterns) backed by Parse via the existing Parse JS API and custom graphql-like endpoints on CloudCode.  

Would love to take advantage of the work done here (observe subs, optimistic updates, mutations, query batching, etc) if at all possible.

Thanks in advance.

**Comment by chadobado** [comment]
For anyone interested, it was fairly trivial to decouple the react dependencies.  Took me about an hour, matching the lifecycle methods used in the mixin, and adding appropriate function binds where needed (as react autobinds by default to maintain correct function scope).

**Comment by andrewimm** [comment]
All of the code is very loosely coupled with React. The move to a truly Observable interface mentioned in #1 should actually help you, since it reduces the amount of React surface area you need to recreate.

That being said, we don't have any plans right now to decouple this from React, but hack away! That's why we made it open source.
