### ISSUE TITLE
Decrement Mutations

### ISSUE THREAD

**Issue by agnosticdev** [ParsePlatform/ParseReact#34]
I've run into a situation where the Increment Mutation has proved very useful, it keeps the client from writing stale data to Parse and keeps the update to the UI very quick and snappy.
I was looking through the docs and Mutation.js and noticed that there is not a Decrement Mutation.  I realize a Decrement Mutation proves to be a bit more tricky that an Increment Mutation because of negative numbers, but I was wondering if anything was in the works for this Mutation or if this is something that could be submitted as a future pull request?

**Comment by andrewimm** [comment]
Actually, the Increment operator takes an optional parameter that lets you specify the amount to increment by. We recommend Incrementing by a negative number to achieve the functionality you're looking for.
This is the same API found in the Parse SDKs. Personally, I'm against adding a mutation that duplicates the functionality of another, because this library follows in the React style of providing a minimalist API.

**Comment by agnosticdev** [comment]
I would agree, I will try this approach.  Thank you.
