### ISSUE TITLE
difficulty with matchesQuery constraint in subscribed query

### ISSUE THREAD

**Issue by jackphel** [ParsePlatform/ParseReact#74]
A `matchesQuery` constraint in a subscribed query seems destined to come to 
https://github.com/ParsePlatform/ParseReact/blob/master/src/QueryTools.js#L297
from the condition string `$inQuery` after a matching mutation is dispatched. So, the mutation doesn't trigger a ui rerender.

I'm not very sure about the bigger picture so this is probably naive, but in the above switch statement would:
```js
case '$inQuery':
  return true;
```
cause any problems since it's overly permissive in claiming matches? It seems to remedy my situation.

**Comment by andrewimm** [comment]
It would indeed cause issues, because the query subscription model would no longer be valid -- developers subscribing to queries that rely on the results from other queries would suddenly find that many (or all) objects of a specific class would be pushed to their components. In scenarios where we can't reliably estimate whether a query will match a component, we err on the side of failure, because a UI that doesn't automatically update is better than one that behaves unpredictably.

However, if you really need to use the results from a nested query, there's an easy way to orchestrate this to automatically update. If you had Comments that pointed to parent Posts, and you wanted to fetch the Comments for all Posts with images, you could first fetch the Posts (inner query) and use those ids to fetch the comments:
```js
var A = React.createComponent({
  observe() {
    return { posts: new Parse.Query('Post').exists('image') };
  }
  
  render() {
    var postIds = this.data.posts.map((post) => {
      var p = new Parse.Object('Post');
      p.id = post.id.objectId;
      return p
    });
    return <B postIds={postIds} />;
  }
});

var B = React.createComponent({
  observe(props) {
    if (!props.postIds.length) {
      return {};
    }
    return { comments: new Parse.Query('Comment').containedIn('post', props.postIds) };
  }
});
```
(That `.map()` clause should be avoidable / significantly cleaned up with a patch I plan on releasing later today, which will make it easier to query with flattened objects)

**Comment by jackphel** [comment]
I see. I ended up doing exactly that!
