### ISSUE TITLE
Refresh queries from components that don't observe it.

### ISSUE THREAD

**Issue by Nicktho** [ParsePlatform/ParseReact#76]
Maybe I'm missing something.. but I can't seem to figure out how to update queries to go fetch data from the server unless I call `this.refeshQueries()` from the component. 

Much like how `ParseReact.Mutation.Create('class', {})` creates an object locally and saves it to parse then tells all components observing it about it, is there some way to do the equivalent of `ParseReact.Mutation.Refresh('class')` to refresh all the queries on that class to pull it from the server? 

Perhaps I'm just not understanding it correctly, but the reason I ask is, if I had a component that calls `ParseReact.Mutation.Create('class', {})`, all other components observing that class will receive the new object, but they _won't_ receive any new objects that exist on the server until those components call `this.refreshQueries()`.

For example: 
In a collaborative todo app, where all users can see the same list. 
User A loads the app, User B loads the app after User A. 
User B creates a new todo, "Pick up trash", a few minutes go by, then...
User A creates a new todo, "Walk the dog".
Even though by this point the "Pick up trash" todo exists on Parse, when User A creates the new todo, and `ParseReact.Mutation.Create('Todo', {desc: 'Walk the dog'})` is called, and the server comes back with an okay, User A won't see User B's todo, `Pick up Trash`. The only way I can see to trigger this is either a hard page-refresh or calling `this.refreshQueries()` in the component that is responsible for the list of todos. 

I assumed that this would also fetch any new todos from the server, from the documentation:
```
Each time the query is re-issued, or objects are modified locally that match the query, it will update itself to reflect these changes.
```

**Comment by Nicktho** [comment]
I know this is technically possible because if I call `this.refreshQueries()` on a component that observes the same query to another component, they will both update.

**Comment by Nicktho** [comment]
What I'm looking for is some way to refresh the queries for all components of a certain class.

**Comment by andrewimm** [comment]
I'll make some edits to clarify the documentation. When an object is created/modified locally, we match it to any local queries precisely in order to avoid query refreshes. This makes responding to local updates extremely efficient.
The core issue is that queries are still fetched by polling -- you can't know which objects are created by other clients without explicitly requesting them, and there's no way to get only the information on which objects have been added or removed from a given query without maintaining state on the server. In any polling application, you need to either explicitly refresh the query on a user action (when a button is pressed, when contents are updated) or on a timer (every minute, etc). This is something that's very application-specific, so I can't provide any advice on how to approach this, but I will say that refreshing all queries for a given class sounds dangerously inefficient. If you have a few queries that all should be refreshed together, I'd recommend keeping them in a single component, and then passing their contents down via `props` or `context`.

Something like:
```js
<DataComponent> // This is where you make your observations
  <DataViewerA props={this.data.a} />
  <DataViewerB props={this.data.b} />
  <DataViewerC props={this.data.c} />
</DataComponent>
```
That way, you have a central location from which to execute your refreshes. The Flux/Parse+React pattern is to avoid disparate components from falling out of sync, so it encourages keeping refreshes together if possible.

**Comment by Nicktho** [comment]
Thanks for the clarification andrew, it's helped quited a bit.
